#ifndef CONSTANTES
#define CONSTANTES

static int CONSTANTE_HASHEO = 5381;
static float POTENCIA_TAMANO_BUCKETS = 22.0/30.0;

static int TAMANO_INICIAL_LISTA = 1024;
static int LARGO_MAXIMO_PALABRA = 500;

#endif
